# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [4]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

height = np.array(height)
weight = np.array(weight)
print(height, weight)

weight / (height**2) * 730


[69 70 71 72 73 74 75] [110 120 130 140 150 160 170]


array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [34]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

# Version that prompts for user input but lacks data type customization:

def makeMatrix1():

    matrix_low = input('provide lowest num for matrix')
    if matrix_low:
        matrix_high = input('provide highest num for matrix')
    if matrix_high:
        matrix_cols = input('provide number of columns')
    if matrix_cols:
        matrix_rows = input('provide number of rows')
    if matrix_rows:
        # print(matrix_low, matrix_high, matrix_cols, matrix_rows)
        print('makeMatrix1 output:')
        print(np.random.uniform( int(matrix_low), int(matrix_high), (int(matrix_rows), int(matrix_cols)) ))
makeMatrix1()

# Version without user input prompts but with data type customization:

def makeMatrix2(low,high,shape,data_type = float):
    
    return np.random.uniform( int(low), int(high), int(shape[0])**2 ).reshape(shape)    

print('makeMatrix2 output:')
print(makeMatrix2(1,10,(3,3),data_type = float))


provide lowest num for matrix1
provide highest num for matrix10
provide number of columns5
provide number of rows5
makeMatrix1 output:
[[9.46416014 9.84769828 5.86112541 1.84792299 4.93246767]
 [9.99287157 2.73848042 5.98070156 6.27085324 1.95396679]
 [8.57917518 8.74112003 6.53702807 7.4192916  2.17623321]
 [3.27954272 5.74833654 6.52618607 6.54585079 4.95369741]
 [6.10476447 9.46110042 9.34090553 4.32762802 7.69290252]]
makeMatrix2 output:
[[8.49663032 7.32192694 3.95979846]
 [8.52212346 1.38814323 4.49536627]
 [3.06519613 5.56936787 8.34348863]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [37]:
import csv
import numpy as np

#Test to make sure you have the correct data

# Return data in csv format

def open_csv(filename, d = ','):
    #define empty list to store data
    data = []
    
    with open(filename, encoding = 'utf-8') as mData: #with open more memory-efficient
        # use csv to create a python list
        info = csv.reader(mData, delimiter=d)
        
        #loop over info and append to data list
        for row in info:
            data.append(row)
    return data
csv_data_2017 = open_csv('./files/redsox_2017_hitting.txt')
csv_data_2018 = open_csv('./files/redsox_2018_hitting.txt')

print(csv_data_2017[0:5])
print(csv_data_2018[0:5])



[['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB'], ['1', 'C', 'Christian Vazquez', '26', '99', '345', '324', '43', '94', '18', '2', '5', '32', '7', '2', '17', '64', '.290', '.330', '.404', '.735', '91', '131', '14', '3', '0', '1', '0'], ['2', '1B', 'Mitch Moreland', '31', '149', '576', '508', '73', '125', '34', '0', '22', '79', '0', '1', '57', '120', '.246', '.326', '.443', '.769', '99', '225', '14', '6', '0', '5', '6'], ['3', '2B', 'Dustin Pedroia', '33', '105', '463', '406', '46', '119', '19', '0', '7', '62', '4', '3', '49', '48', '.293', '.369', '.392', '.760', '100', '159', '11', '2', '2', '4', '4'], ['4', 'SS', 'Xander Bogaerts', '24', '148', '635', '571', '94', '156', '32', '6', '10', '62', '15', '1', '56', '116', '.273', '.343', '.403', '.746', '95', '230', '17', '6', '0', '2', '6']]
[['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B',

In [47]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d=','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1, usecols = np.arange(0,24), invalid_raise = False, names = FIELDS, dtype=DATATYPES)
    return data

bs2017 = load_data('./files/redsox_2017_hitting.txt')
# print(bs2017['SLG'])
bs2017_SLG = bs2017['SLG']
bs2017_SLG_sum = sum(bs2017['SLG'])
# print(bs2017_SLG_sum)
bs2018 = load_data('./files/redsox_2018_hitting.txt')
# print(bs2018['SLG'])
bs2018_SLG = bs2018['SLG']
bs2018_SLG_sum = sum(bs2018['SLG'])
# print(bs2018_SLG_sum)

if bs2017_SLG_sum > bs2018_SLG_sum:
    print(f'Boston had more SLG in 2017 than 2018. Total SLG: {bs2017_SLG_sum}\nSLG: {bs2017_SLG}')
else:
    print(f'Boston had more SLG in 2018 than 2017. Total SLG: {bs2018_SLG_sum}\nSLG: {bs2018_SLG}')



[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
9.04699994623661
[0.279 0.433 0.388 0.522 0.433 0.465 0.403 0.64  0.629 0.411 0.283 0.328
 0.395 0.507 0.311 0.415 0.389 0.261 0.091 0.167]
7.750000067055225
Boston had more SLG in 2017 than 2018. Total SLG: 9.04699994623661
SLG: [0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
